# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170502_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
